<?php

use Database\traits\DisableForeignKeys;
use Database\traits\TruncateTable;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon as Carbon;

class CurrencyTableSeeder extends Seeder
{
    use TruncateTable, DisableForeignKeys;

    public function run()
    {
        $this->truncate('currencies');

        $currencies = [

            [
                'country' => 'AFGHANISTAN',
                'currency' => 'Afghani',
                'code' => 'AFN',
                'number' => '971',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ALBANIA',
                'currency' => 'Lek',
                'code' => 'ALL',
                'number' => '008',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => 'ALGERIA',
                'currency' => 'Algerian Dinar',
                'code' => 'DZD',
                'number' => '012',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'AMERICAN SAMOA',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'country' => 'ANDORRA',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ANGOLA',
                'currency' => 'Kwanza',
                'code' => 'AOA',
                'number' => '973',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ANGUILLA',
                'currency' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'number' => '951',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ANTIGUA AND BARBUDA',
                'currency' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'number' => '951',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ARGENTINA',
                'currency' => 'Argentine Peso',
                'code' => 'ARS',
                'number' => '032',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ARMENIA',
                'currency' => 'Armenian Dram',
                'code' => 'AMD',
                'number' => '051',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ARUBA',
                'currency' => 'Aruban Florin',
                'code' => 'AWG',
                'number' => '533',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'AUSTRALIA',
                'currency' => 'Australian Dollar',
                'code' => 'AUD',
                'number' => '036',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'AUSTRIA',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'AZERBAIJAN',
                'currency' => 'Azerbaijan Manat',
                'code' => 'AZN',
                'number' => '944',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BAHAMAS (THE)',
                'currency' => 'Bahamian Dollar',
                'code' => 'BSD',
                'number' => '044',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BAHRAIN',
                'currency' => 'Bahraini Dinar',
                'code' => 'BHD',
                'number' => '048',
                'units' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BANGLADESH',
                'currency' => 'Taka',
                'code' => 'BDT',
                'number' => '050',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BARBADOS',
                'currency' => 'Barbados Dollar',
                'code' => 'BBD',
                'number' => '052',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BELARUS',
                'currency' => 'Belarusian Ruble',
                'code' => 'BYN',
                'number' => '933',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BELGIUM',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BELIZE',
                'currency' => 'Belize Dollar',
                'code' => 'BZD',
                'number' => '084',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BENIN',
                'currency' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'number' => '952',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BERMUDA',
                'currency' => 'Bermudian Dollar',
                'code' => 'BMD',
                'number' => '060',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BHUTAN',
                'currency' => 'Indian Rupee',
                'code' => 'INR',
                'number' => '356',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BHUTAN',
                'currency' => 'Ngultrum',
                'code' => 'BTN',
                'number' => '064',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BOLIVIA (PLURINATIONAL STATE OF)',
                'currency' => 'Boliviano',
                'code' => 'BOB',
                'number' => '068',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BONAIRE, SINT EUSTATIUS AND SABA',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BOSNIA AND HERZEGOVINA',
                'currency' => 'Convertible Mark',
                'code' => 'BAM',
                'number' => '977',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BOTSWANA',
                'currency' => 'Pula',
                'code' => 'BWP',
                'number' => '072',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BOUVET ISLAND',
                'currency' => 'Norwegian Krone',
                'code' => 'NOK',
                'number' => '578',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BRAZIL',
                'currency' => 'Brazilian Real',
                'code' => 'BRL',
                'number' => '986',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BRITISH INDIAN OCEAN TERRITORY (THE)',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BRUNEI DARUSSALAM',
                'currency' => 'Brunei Dollar',
                'code' => 'BND',
                'number' => '096',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BULGARIA',
                'currency' => 'Bulgarian Lev',
                'code' => 'BGN',
                'number' => '975',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BURKINA FASO',
                'currency' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'number' => '952',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'BURUNDI',
                'currency' => 'Burundi Franc',
                'code' => 'BIF',
                'number' => '108',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CABO VERDE',
                'currency' => 'Cabo Verde Escudo',
                'code' => 'CVE',
                'number' => '132',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CAMBODIA',
                'currency' => 'Riel',
                'code' => 'KHR',
                'number' => '116',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CAMEROON',
                'currency' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'number' => '950',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CANADA',
                'currency' => 'Canadian Dollar',
                'code' => 'CAD',
                'number' => '124',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CAYMAN ISLANDS (THE)',
                'currency' => 'Cayman Islands Dollar',
                'code' => 'KYD',
                'number' => '136',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CENTRAL AFRICAN REPUBLIC (THE)',
                'currency' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'number' => '950',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CHAD',
                'currency' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'number' => '950',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CHILE',
                'currency' => 'Chilean Peso',
                'code' => 'CLP',
                'number' => '152',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CHILE',
                'currency' => 'Unidad de Fomento',
                'code' => 'CLF',
                'number' => '990',
                'units' => '4',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CHINA',
                'currency' => 'Yuan Renminbi',
                'code' => 'CNY',
                'number' => '156',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CHRISTMAS ISLAND',
                'currency' => 'Australian Dollar',
                'code' => 'AUD',
                'number' => '036',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'COCOS (KEELING) ISLANDS (THE)',
                'currency' => 'Australian Dollar',
                'code' => 'AUD',
                'number' => '036',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'COLOMBIA',
                'currency' => 'Colombian Peso',
                'code' => 'COP',
                'number' => '170',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'COMOROS (THE)',
                'currency' => 'Comorian Franc ',
                'code' => 'KMF',
                'number' => '174',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
                'currency' => 'Congolese Franc',
                'code' => 'CDF',
                'number' => '976',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CONGO (THE)',
                'currency' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'number' => '950',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'COOK ISLANDS (THE)',
                'currency' => 'New Zealand Dollar',
                'code' => 'NZD',
                'number' => '554',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'COSTA RICA',
                'currency' => 'Costa Rican Colon',
                'code' => 'CRC',
                'number' => '188',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CÔTE D\'IVOIRE',
                'currency' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'number' => '952',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CROATIA',
                'currency' => 'Kuna',
                'code' => 'HRK',
                'number' => '191',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CUBA',
                'currency' => 'Cuban Peso',
                'code' => 'CUP',
                'number' => '192',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CUBA',
                'currency' => 'Peso Convertible',
                'code' => 'CUC',
                'number' => '931',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CURAÇAO',
                'currency' => 'Netherlands Antillean Guilder',
                'code' => 'ANG',
                'number' => '532',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CYPRUS',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'CZECHIA',
                'currency' => 'Czech Koruna',
                'code' => 'CZK',
                'number' => '203',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'DENMARK',
                'currency' => 'Danish Krone',
                'code' => 'DKK',
                'number' => '208',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'DJIBOUTI',
                'currency' => 'Djibouti Franc',
                'code' => 'DJF',
                'number' => '262',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'DOMINICA',
                'currency' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'number' => '951',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'DOMINICAN REPUBLIC (THE)',
                'currency' => 'Dominican Peso',
                'code' => 'DOP',
                'number' => '214',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ECUADOR',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'EGYPT',
                'currency' => 'Egyptian Pound',
                'code' => 'EGP',
                'number' => '818',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'EL SALVADOR',
                'currency' => 'El Salvador Colon',
                'code' => 'SVC',
                'number' => '222',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'EL SALVADOR',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'EQUATORIAL GUINEA',
                'currency' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'number' => '950',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ERITREA',
                'currency' => 'Nakfa',
                'code' => 'ERN',
                'number' => '232',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ESTONIA',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ESWATINI',
                'currency' => 'Lilangeni',
                'code' => 'SZL',
                'number' => '748',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ETHIOPIA',
                'currency' => 'Ethiopian Birr',
                'code' => 'ETB',
                'number' => '230',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'country' => 'EUROPEAN UNION',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'FALKLAND ISLANDS (THE) [MALVINAS]',
                'currency' => 'Falkland Islands Pound',
                'code' => 'FKP',
                'number' => '238',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'FAROE ISLANDS (THE)',
                'currency' => 'Danish Krone',
                'code' => 'DKK',
                'number' => '208',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'FIJI',
                'currency' => 'Fiji Dollar',
                'code' => 'FJD',
                'number' => '242',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'FINLAND',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'FRANCE',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'FRENCH GUIANA',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'FRENCH POLYNESIA',
                'currency' => 'CFP Franc',
                'code' => 'XPF',
                'number' => '953',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'FRENCH SOUTHERN TERRITORIES (THE)',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GABON',
                'currency' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'number' => '950',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GAMBIA (THE)',
                'currency' => 'Dalasi',
                'code' => 'GMD',
                'number' => '270',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GEORGIA',
                'currency' => 'Lari',
                'code' => 'GEL',
                'number' => '981',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GERMANY',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GHANA',
                'currency' => 'Ghana Cedi',
                'code' => 'GHS',
                'number' => '936',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GIBRALTAR',
                'currency' => 'Gibraltar Pound',
                'code' => 'GIP',
                'number' => '292',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GREECE',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GREENLAND',
                'currency' => 'Danish Krone',
                'code' => 'DKK',
                'number' => '208',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GRENADA',
                'currency' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'number' => '951',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GUADELOUPE',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GUAM',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GUATEMALA',
                'currency' => 'Quetzal',
                'code' => 'GTQ',
                'number' => '320',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GUERNSEY',
                'currency' => 'Pound Sterling',
                'code' => 'GBP',
                'number' => '826',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GUINEA',
                'currency' => 'Guinean Franc',
                'code' => 'GNF',
                'number' => '324',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GUINEA-BISSAU',
                'currency' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'number' => '952',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'GUYANA',
                'currency' => 'Guyana Dollar',
                'code' => 'GYD',
                'number' => '328',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'HAITI',
                'currency' => 'Gourde',
                'code' => 'HTG',
                'number' => '332',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'HAITI',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'HEARD ISLAND AND McDONALD ISLANDS',
                'currency' => 'Australian Dollar',
                'code' => 'AUD',
                'number' => '036',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'HOLY SEE (THE)',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'HONDURAS',
                'currency' => 'Lempira',
                'code' => 'HNL',
                'number' => '340',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'HONG KONG',
                'currency' => 'Hong Kong Dollar',
                'code' => 'HKD',
                'number' => '344',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'HUNGARY',
                'currency' => 'Forint',
                'code' => 'HUF',
                'number' => '348',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ICELAND',
                'currency' => 'Iceland Krona',
                'code' => 'ISK',
                'number' => '352',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'INDIA',
                'currency' => 'Indian Rupee',
                'code' => 'INR',
                'number' => '356',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'INDONESIA',
                'currency' => 'Rupiah',
                'code' => 'IDR',
                'number' => '360',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'IRAN (ISLAMIC REPUBLIC OF)',
                'currency' => 'Iranian Rial',
                'code' => 'IRR',
                'number' => '364',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'IRAQ',
                'currency' => 'Iraqi Dinar',
                'code' => 'IQD',
                'number' => '368',
                'units' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'IRELAND',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ISLE OF MAN',
                'currency' => 'Pound Sterling',
                'code' => 'GBP',
                'number' => '826',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ISRAEL',
                'currency' => 'New Israeli Sheqel',
                'code' => 'ILS',
                'number' => '376',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ITALY',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'JAMAICA',
                'currency' => 'Jamaican Dollar',
                'code' => 'JMD',
                'number' => '388',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'JAPAN',
                'currency' => 'Yen',
                'code' => 'JPY',
                'number' => '392',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'JERSEY',
                'currency' => 'Pound Sterling',
                'code' => 'GBP',
                'number' => '826',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'JORDAN',
                'currency' => 'Jordanian Dinar',
                'code' => 'JOD',
                'number' => '400',
                'units' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'KAZAKHSTAN',
                'currency' => 'Tenge',
                'code' => 'KZT',
                'number' => '398',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'KENYA',
                'currency' => 'Kenyan Shilling',
                'code' => 'KES',
                'number' => '404',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'KIRIBATI',
                'currency' => 'Australian Dollar',
                'code' => 'AUD',
                'number' => '036',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)',
                'currency' => 'North Korean Won',
                'code' => 'KPW',
                'number' => '408',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'KOREA (THE REPUBLIC OF)',
                'currency' => 'Won',
                'code' => 'KRW',
                'number' => '410',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'KUWAIT',
                'currency' => 'Kuwaiti Dinar',
                'code' => 'KWD',
                'number' => '414',
                'units' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'KYRGYZSTAN',
                'currency' => 'Som',
                'code' => 'KGS',
                'number' => '417',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)',
                'currency' => 'Lao Kip',
                'code' => 'LAK',
                'number' => '418',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'LATVIA',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'LEBANON',
                'currency' => 'Lebanese Pound',
                'code' => 'LBP',
                'number' => '422',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'LESOTHO',
                'currency' => 'Loti',
                'code' => 'LSL',
                'number' => '426',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'LESOTHO',
                'currency' => 'Rand',
                'code' => 'ZAR',
                'number' => '710',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'LIBERIA',
                'currency' => 'Liberian Dollar',
                'code' => 'LRD',
                'number' => '430',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'LIBYA',
                'currency' => 'Libyan Dinar',
                'code' => 'LYD',
                'number' => '434',
                'units' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'LIECHTENSTEIN',
                'currency' => 'Swiss Franc',
                'code' => 'CHF',
                'number' => '756',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'LITHUANIA',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'LUXEMBOURG',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MACAO',
                'currency' => 'Pataca',
                'code' => 'MOP',
                'number' => '446',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NORTH MACEDONIA',
                'currency' => 'Denar',
                'code' => 'MKD',
                'number' => '807',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MADAGASCAR',
                'currency' => 'Malagasy Ariary',
                'code' => 'MGA',
                'number' => '969',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MALAWI',
                'currency' => 'Malawi Kwacha',
                'code' => 'MWK',
                'number' => '454',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MALAYSIA',
                'currency' => 'Malaysian Ringgit',
                'code' => 'MYR',
                'number' => '458',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MALDIVES',
                'currency' => 'Rufiyaa',
                'code' => 'MVR',
                'number' => '462',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MALI',
                'currency' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'number' => '952',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MALTA',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MARSHALL ISLANDS (THE)',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MARTINIQUE',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MAURITANIA',
                'currency' => 'Ouguiya',
                'code' => 'MRU',
                'number' => '929',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MAURITIUS',
                'currency' => 'Mauritius Rupee',
                'code' => 'MUR',
                'number' => '480',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MAYOTTE',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MEXICO',
                'currency' => 'Mexican Peso',
                'code' => 'MXN',
                'number' => '484',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MOLDOVA (THE REPUBLIC OF)',
                'currency' => 'Moldovan Leu',
                'code' => 'MDL',
                'number' => '498',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MONACO',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MONGOLIA',
                'currency' => 'Tugrik',
                'code' => 'MNT',
                'number' => '496',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MONTENEGRO',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MONTSERRAT',
                'currency' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'number' => '951',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MOROCCO',
                'currency' => 'Moroccan Dirham',
                'code' => 'MAD',
                'number' => '504',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MOZAMBIQUE',
                'currency' => 'Mozambique Metical',
                'code' => 'MZN',
                'number' => '943',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'MYANMAR',
                'currency' => 'Kyat',
                'code' => 'MMK',
                'number' => '104',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NAMIBIA',
                'currency' => 'Namibia Dollar',
                'code' => 'NAD',
                'number' => '516',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NAMIBIA',
                'currency' => 'Rand',
                'code' => 'ZAR',
                'number' => '710',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NAURU',
                'currency' => 'Australian Dollar',
                'code' => 'AUD',
                'number' => '036',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NEPAL',
                'currency' => 'Nepalese Rupee',
                'code' => 'NPR',
                'number' => '524',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NETHERLANDS (THE)',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NEW CALEDONIA',
                'currency' => 'CFP Franc',
                'code' => 'XPF',
                'number' => '953',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NEW ZEALAND',
                'currency' => 'New Zealand Dollar',
                'code' => 'NZD',
                'number' => '554',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NICARAGUA',
                'currency' => 'Cordoba Oro',
                'code' => 'NIO',
                'number' => '558',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NIGER (THE)',
                'currency' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'number' => '952',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NIGERIA',
                'currency' => 'Naira',
                'code' => 'NGN',
                'number' => '566',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NIUE',
                'currency' => 'New Zealand Dollar',
                'code' => 'NZD',
                'number' => '554',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NORFOLK ISLAND',
                'currency' => 'Australian Dollar',
                'code' => 'AUD',
                'number' => '036',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NORTHERN MARIANA ISLANDS (THE)',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'NORWAY',
                'currency' => 'Norwegian Krone',
                'code' => 'NOK',
                'number' => '578',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'OMAN',
                'currency' => 'Rial Omani',
                'code' => 'OMR',
                'number' => '512',
                'units' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'PAKISTAN',
                'currency' => 'Pakistan Rupee',
                'code' => 'PKR',
                'number' => '586',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'PALAU',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'country' => 'PANAMA',
                'currency' => 'Balboa',
                'code' => 'PAB',
                'number' => '590',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'PANAMA',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'PAPUA NEW GUINEA',
                'currency' => 'Kina',
                'code' => 'PGK',
                'number' => '598',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'PARAGUAY',
                'currency' => 'Guarani',
                'code' => 'PYG',
                'number' => '600',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'PERU',
                'currency' => 'Sol',
                'code' => 'PEN',
                'number' => '604',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'PHILIPPINES (THE)',
                'currency' => 'Philippine Peso',
                'code' => 'PHP',
                'number' => '608',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'PITCAIRN',
                'currency' => 'New Zealand Dollar',
                'code' => 'NZD',
                'number' => '554',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'POLAND',
                'currency' => 'Zloty',
                'code' => 'PLN',
                'number' => '985',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'PORTUGAL',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'PUERTO RICO',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'QATAR',
                'currency' => 'Qatari Rial',
                'code' => 'QAR',
                'number' => '634',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'RÉUNION',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ROMANIA',
                'currency' => 'Romanian Leu',
                'code' => 'RON',
                'number' => '946',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'RUSSIAN FEDERATION (THE)',
                'currency' => 'Russian Ruble',
                'code' => 'RUB',
                'number' => '643',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'RWANDA',
                'currency' => 'Rwanda Franc',
                'code' => 'RWF',
                'number' => '646',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SAINT BARTHÉLEMY',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
                'currency' => 'Saint Helena Pound',
                'code' => 'SHP',
                'number' => '654',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SAINT KITTS AND NEVIS',
                'currency' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'number' => '951',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SAINT LUCIA',
                'currency' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'number' => '951',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SAINT MARTIN (FRENCH PART)',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SAINT PIERRE AND MIQUELON',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SAINT VINCENT AND THE GRENADINES',
                'currency' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'number' => '951',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SAMOA',
                'currency' => 'Tala',
                'code' => 'WST',
                'number' => '882',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SAN MARINO',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SAO TOME AND PRINCIPE',
                'currency' => 'Dobra',
                'code' => 'STN',
                'number' => '930',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SAUDI ARABIA',
                'currency' => 'Saudi Riyal',
                'code' => 'SAR',
                'number' => '682',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SENEGAL',
                'currency' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'number' => '952',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SERBIA',
                'currency' => 'Serbian Dinar',
                'code' => 'RSD',
                'number' => '941',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SEYCHELLES',
                'currency' => 'Seychelles Rupee',
                'code' => 'SCR',
                'number' => '690',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SIERRA LEONE',
                'currency' => 'Leone',
                'code' => 'SLL',
                'number' => '694',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SINGAPORE',
                'currency' => 'Singapore Dollar',
                'code' => 'SGD',
                'number' => '702',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SINT MAARTEN (DUTCH PART)',
                'currency' => 'Netherlands Antillean Guilder',
                'code' => 'ANG',
                'number' => '532',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SLOVAKIA',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SLOVENIA',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SOLOMON ISLANDS',
                'currency' => 'Solomon Islands Dollar',
                'code' => 'SBD',
                'number' => '090',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SOMALIA',
                'currency' => 'Somali Shilling',
                'code' => 'SOS',
                'number' => '706',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SOUTH AFRICA',
                'currency' => 'Rand',
                'code' => 'ZAR',
                'number' => '710',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],  [
                'country' => 'SOUTH SUDAN',
                'currency' => 'South Sudanese Pound',
                'code' => 'SSP',
                'number' => '728',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SPAIN',
                'currency' => 'Euro',
                'code' => 'EUR',
                'number' => '978',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SRI LANKA',
                'currency' => 'Sri Lanka Rupee',
                'code' => 'LKR',
                'number' => '144',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SUDAN (THE)',
                'currency' => 'Sudanese Pound',
                'code' => 'SDG',
                'number' => '938',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SURINAME',
                'currency' => 'Surinam Dollar',
                'code' => 'SRD',
                'number' => '968',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SVALBARD AND JAN MAYEN',
                'currency' => 'Norwegian Krone',
                'code' => 'NOK',
                'number' => '578',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SWEDEN',
                'currency' => 'Swedish Krona',
                'code' => 'SEK',
                'number' => '752',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SWITZERLAND',
                'currency' => 'Swiss Franc',
                'code' => 'CHF',
                'number' => '756',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'SYRIAN ARAB REPUBLIC',
                'currency' => 'Syrian Pound',
                'code' => 'SYP',
                'number' => '760',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TAIWAN (PROVINCE OF CHINA)',
                'currency' => 'New Taiwan Dollar',
                'code' => 'TWD',
                'number' => '901',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TAJIKISTAN',
                'currency' => 'Somoni',
                'code' => 'TJS',
                'number' => '972',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TANZANIA, UNITED REPUBLIC OF',
                'currency' => 'Tanzanian Shilling',
                'code' => 'TZS',
                'number' => '834',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'THAILAND',
                'currency' => 'Baht',
                'code' => 'THB',
                'number' => '764',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TIMOR-LESTE',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TOGO',
                'currency' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'number' => '952',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TOKELAU',
                'currency' => 'New Zealand Dollar',
                'code' => 'NZD',
                'number' => '554',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TONGA',
                'currency' => 'Pa’anga',
                'code' => 'TOP',
                'number' => '776',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TRINIDAD AND TOBAGO',
                'currency' => 'Trinidad and Tobago Dollar',
                'code' => 'TTD',
                'number' => '780',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TUNISIA',
                'currency' => 'Tunisian Dinar',
                'code' => 'TND',
                'number' => '788',
                'units' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TURKEY',
                'currency' => 'Turkish Lira',
                'code' => 'TRY',
                'number' => '949',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'country' => 'TURKMENISTAN',
                'currency' => 'Turkmenistan New Manat',
                'code' => 'TMT',
                'number' => '934',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TURKS AND CAICOS ISLANDS (THE)',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'TUVALU',
                'currency' => 'Australian Dollar',
                'code' => 'AUD',
                'number' => '036',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'UGANDA',
                'currency' => 'Uganda Shilling',
                'code' => 'UGX',
                'number' => '800',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'UKRAINE',
                'currency' => 'Hryvnia',
                'code' => 'UAH',
                'number' => '980',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'UNITED ARAB EMIRATES (THE)',
                'currency' => 'UAE Dirham',
                'code' => 'AED',
                'number' => '784',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
                'currency' => 'Pound Sterling',
                'code' => 'GBP',
                'number' => '826',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'UNITED STATES MINOR OUTLYING ISLANDS (THE)',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'UNITED STATES OF AMERICA (THE)',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'URUGUAY',
                'currency' => 'Peso Uruguayo',
                'code' => 'UYU',
                'number' => '858',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'UZBEKISTAN',
                'currency' => 'Uzbekistan Sum',
                'code' => 'UZS',
                'number' => '860',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'VANUATU',
                'currency' => 'Vatu',
                'code' => 'VUV',
                'number' => '548',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
                'currency' => 'Bolívar Soberano',
                'code' => 'VES',
                'number' => '928',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'VIET NAM',
                'currency' => 'Dong',
                'code' => 'VND',
                'number' => '704',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'VIRGIN ISLANDS (BRITISH)',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'VIRGIN ISLANDS (U.S.)',
                'currency' => 'US Dollar',
                'code' => 'USD',
                'number' => '840',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'WALLIS AND FUTUNA',
                'currency' => 'CFP Franc',
                'code' => 'XPF',
                'number' => '953',
                'units' => '0',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'WESTERN SAHARA',
                'currency' => 'Moroccan Dirham',
                'code' => 'MAD',
                'number' => '504',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'YEMEN',
                'currency' => 'Yemeni Rial',
                'code' => 'YER',
                'number' => '886',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'country' => 'ZAMBIA',
                'currency' => 'Zambian Kwacha',
                'code' => 'ZMW',
                'number' => '967',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'country' => 'ZIMBABWE',
                'currency' => 'Zimbabwe Dollar',
                'code' => 'ZWL',
                'number' => '932',
                'units' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]

        ];

        DB::table('currencies')->insert($currencies);
    }
}
